#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

### Autostart ###

setxkbmap us &
nitrogen --restore &

eww open bar0 &
eww open bar1 &


### Monitors ###

bspc monitor DP-0 -d 1 2 3
bspc monitor DP-4 -d 4 5 6  



### General config ###

bspc config border_width         1
bspc config window_gap         	 9 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback_color "#7cacd4"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xdo below -t $(xdo id -n root) $(xdo id -a polybar-HDMI-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-DP-4)
